# Generated by Django 4.2 on 2023-07-05 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_useraddress_user_alter_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
