# Generated by Django 4.2 on 2023-06-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="slug",
            field=models.CharField(default="P2BG84SSYTcZSgwS2uFZBC", max_length=255),
        ),
    ]
