# Generated by Django 4.2 on 2023-04-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "High priority"),
                    (2, "Medium priority"),
                    (3, "Low priority"),
                ],
                default=2,
            ),
        ),
    ]
