# Generated by Django 4.2 on 2023-04-18 01:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0002_alter_listitem_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listitemcategory",
            options={"verbose_name_plural": "List item categories"},
        ),
        migrations.AddField(
            model_name="list",
            name="cover_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="custom_route",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="list",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="list",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="note",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="listitemcategory",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="listitemcategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="ListImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("image", models.CharField(max_length=255)),
                (
                    "list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="lists.list",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
