# Generated by Django 4.2 on 2023-06-20 22:48

from django.db import migrations, models
import lists.validators


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0005_list_event_date_alter_list_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="event_date",
            field=models.DateField(validators=[lists.validators.validate_event_date]),
        ),
        migrations.AlterField(
            model_name="list",
            name="slug",
            field=models.CharField(default="HW9WxpJ93MdRBmuFJx6N9G", max_length=255),
        ),
    ]
