# Generated by Django 4.2 on 2023-06-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_listaddress_alter_list_collection_list_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='custom_route',
        ),
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.CharField(default='aJxUM45TQRPEY7GY7D2pt7', max_length=255),
        ),
    ]
