# Generated by Django 4.2 on 2023-06-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0006_alter_list_event_date_alter_list_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_lists",
                to="lists.listcollection",
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="slug",
            field=models.CharField(default="W83qbiAFHKFxYSsDRBsPWR", max_length=255),
        ),
    ]
