# Generated by Django 4.2 on 2023-06-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_remove_list_custom_route_list_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.CharField(default='gWNaDSGBsw9ZHzwQTPZbfs', max_length=255),
        ),
    ]
