# Generated by Django 4.2 on 2023-07-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0007_alter_list_collection_alter_list_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="slug",
            field=models.CharField(default="LDxYDYMSLoGg9UP8QvFBov", max_length=255),
        ),
    ]
