# Generated by Django 4.2 on 2023-07-05 23:59

from django.db import migrations, models
import lists.models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0008_alter_list_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="slug",
            field=models.CharField(
                default=lists.models.create_unique_slug, max_length=255, unique=True
            ),
        ),
    ]
