# Generated by Django 4.2 on 2023-06-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_listaddress_uuid_listcollection_uuid_listimage_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.CharField(default='C7JNmi64d8GHdTJsArdVg8', max_length=255),
        ),
    ]
