# Generated by Django 4.2 on 2023-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_alter_list_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.CharField(default='V5GGuAjttFqPqh6CjTE3Y8', max_length=255),
        ),
    ]
